package io.yukkuric.hexjsneo.kubejs.probe

import io.yukkuric.hexjsneo.kubejs.KJSPluginHJS
import io.yukkuric.hexjsneo.kubejs.probe.llm.apiLevelMembers
import io.yukkuric.hexjsneo.kubejs.probe.llm.apiRegisterNestedDocs
import io.yukkuric.hexjsneo.kubejs.sub.HexJS
import io.yukkuric.hexjsneo.kubejs.sub.api.APINested
import io.yukkuric.hexjsneo.kubejs.sub.base.HexAPICollector
import io.yukkuric.hexjsneo.kubejs.sub.base.HexAPICollector.ClassesFlat
import io.yukkuric.hexjsneo.kubejs.sub.base.SingletonClassTracker
import io.yukkuric.hexjsneo.kubejs.sub.base.SubClassProvider
import moe.wolfgirl.probejs.plugin.ProbeJSPlugin
import moe.wolfgirl.probejs.typescript.Documents
import moe.wolfgirl.probejs.typescript.document.Types
import moe.wolfgirl.probejs.typescript.document.members.ConstructorDecl
import moe.wolfgirl.probejs.typescript.document.members.FieldDecl
import kotlin.collections.component1
import kotlin.collections.component2

private const val PACKAGE_PREFIX = "io.yukkuric.hexjsneo"

class PJSPluginHJS : ProbeJSPlugin() {
    private val SubClassMapMap = HashMap<Class<*>, HashMap<String, Class<*>>>()

    override fun init() {
        HexAPICollector.init()

        // build subclass mapper
        ClassesFlat.forEach perChild@{ (key, cls) ->
            if ('$' !in key) return@perChild
            val (pre, post) = key.split("$", limit = 2)
            val subClassMap = SubClassMapMap.computeIfAbsent((ClassesFlat[pre] ?: return@perChild)) { HashMap() }
            subClassMap[post] = cls
        }
    }

    override fun transformClass(document: Documents.ClassDocument) {
        val classInfo = document.classInfo()
        val classDocument = document.document()
        val targetCls = classInfo.clazz()
        val packageName = targetCls.packageName

        // clean doc-gen class inners
        if (packageName.startsWith("$PACKAGE_PREFIX.kubejs.sub.base")) {
            classDocument.members.clear()
            return
        }

        // subclass assign
        SubClassMapMap[targetCls]?.let {
            it.forEach { (key, cls) ->
                val field = FieldDecl(key, Types.typeOf(Types.clazz(cls)), true)
                classDocument.members.add(field)
            }
        }

        // basic class nesting
        if (packageName.startsWith("$PACKAGE_PREFIX.casting")) {
            for (subCls in targetCls.declaredClasses) {
                if (subCls.isAnonymousClass) continue
                val field = FieldDecl(
                    subCls.simpleName.removePrefix(targetCls.simpleName),
                    Types.typeOf(Types.clazz(subCls)),
                    true
                )
                classDocument.members.add(field)
            }
        }

        // HexJS dynamic objects
        if (packageName.startsWith("$PACKAGE_PREFIX.kubejs.sub")) {
            // remove inner stuff
            classDocument.members.removeIf rif@{
                if (it is FieldDecl) {
                    if (it.isStatic) return@rif true
                }
                if (it is ConstructorDecl) return@rif true
                false
            }

            // API nested special handler
            if (targetCls == APINested::class.java) {
                // Generated by GLM-5.3
                classDocument.members.addAll(apiLevelMembers(HexAPICollector.ClassesNested, emptyList()))
                return
            }

            // fetch saved fake singleton
            val obj = SingletonClassTracker.from(targetCls) as? SubClassProvider ?: return

            // manual class dump
            for ((name, cls) in obj.contents()) {
                val field = FieldDecl(name, Types.typeOf(Types.clazz(cls)), false)
                classDocument.members.add(field)
            }
        }
    }

    override fun modifyClasses(classDocuments: Documents.ClassAccessor) {
        apiRegisterNestedDocs(classDocuments, HexAPICollector.ClassesNested, emptyList())
    }

    override fun provideClassForDiscovery() = sequence {
        yield(HexJS::class.java)
        yieldAll(SubClassProvider.LOADED_CLASSES)
        yieldAll(HexAPICollector.ClassesFlat.values)
        for (subCls in KJSPluginHJS.CUSTOM_JS_CLASSES) {
            yield(subCls)
            yieldAll(subCls.declaredClasses.filter { !it.isAnonymousClass })
        }
    }.toSet()
}